/* This file was generated by syncqt. */
#ifndef QT_QTUIPLUGIN_VERSION_H
#define QT_QTUIPLUGIN_VERSION_H

#define QTUIPLUGIN_VERSION_STR "5.15.2"

#define QTUIPLUGIN_VERSION 0x050F02

#endif // QT_QTUIPLUGIN_VERSION_H
