/* This file was generated by syncqt. */
#ifndef QT_QTWEBVIEW_VERSION_H
#define QT_QTWEBVIEW_VERSION_H

#define QTWEBVIEW_VERSION_STR "5.15.2"

#define QTWEBVIEW_VERSION 0x050F02

#endif // QT_QTWEBVIEW_VERSION_H
