QT.gui_private.VERSION = 5.15.2
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/5.15.2 $$QT_MODULE_INCLUDE_BASE/QtGui/5.15.2/QtGui
QT.gui_private.frameworks =
QT.gui_private.depends = core_private gui
QT.gui_private.uses =
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = xkbcommon xkbcommon-x11 xcb drm_atomic egl egl_x11 eglfs kms eglfs_egldevice xlib xcb-xlib eglfs_x11 evdev freetype system-freetype fontconfig gif harfbuzz ico imageio-text-loading jpeg multiprocess png raster-64bit system-jpeg system-png system-xcb-xinput tuiotouch vkgen vnc xcb-egl-plugin xcb-glx-plugin xcb-glx xcb-sm
QT.gui_private.disabled_features = accessibility-atspi-bridge angle_d3d11_qdtd direct2d direct2d1_1 dxgi direct3d11 direct3d11_1 direct3d9 directfb dxgi1_2 dxguid eglfs_brcm eglfs_gbm eglfs_mali eglfs_openwfd eglfs_rcar eglfs_viv eglfs_viv_wl eglfs_vsp2 integrityfb integrityhid libinput libinput-axis-api linuxfb mtdev system-harfbuzz tslib vsp2 xcb-native-painting
QMAKE_INCDIR_XCB = /home/james/code/course22/envs/include /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include
QMAKE_DEPENDS_XCB_ICCCM_CC = XCB
QMAKE_DEPENDS_XCB_ICCCM_LD = XCB
QMAKE_DEPENDS_XCB_UTIL_CC = XCB
QMAKE_DEPENDS_XCB_UTIL_LD = XCB
QMAKE_DEPENDS_XCB_SHM_CC = XCB
QMAKE_DEPENDS_XCB_SHM_LD = XCB
QMAKE_DEPENDS_XCB_IMAGE_CC = XCB_SHM XCB_UTIL XCB
QMAKE_DEPENDS_XCB_IMAGE_LD = XCB_SHM XCB_UTIL XCB
QMAKE_DEPENDS_XCB_KEYSYMS_CC = XCB
QMAKE_DEPENDS_XCB_KEYSYMS_LD = XCB
QMAKE_DEPENDS_XCB_RANDR_CC = XCB
QMAKE_DEPENDS_XCB_RANDR_LD = XCB
QMAKE_DEPENDS_XCB_RENDER_CC = XCB
QMAKE_DEPENDS_XCB_RENDER_LD = XCB
QMAKE_DEPENDS_XCB_RENDERUTIL_CC = XCB XCB_RENDER
QMAKE_DEPENDS_XCB_RENDERUTIL_LD = XCB XCB_RENDER
QMAKE_DEPENDS_XCB_SHAPE_CC = XCB
QMAKE_DEPENDS_XCB_SHAPE_LD = XCB
QMAKE_DEPENDS_XCB_SYNC_CC = XCB
QMAKE_DEPENDS_XCB_SYNC_LD = XCB
QMAKE_DEPENDS_XCB_XFIXES_CC = XCB
QMAKE_DEPENDS_XCB_XFIXES_LD = XCB
QMAKE_DEPENDS_XCB_XINERAMA_CC = XCB
QMAKE_DEPENDS_XCB_XINERAMA_LD = XCB
QMAKE_DEPENDS_XCB_XKB_CC = XCB
QMAKE_DEPENDS_XCB_XKB_LD = XCB
QMAKE_INCDIR_XKBCOMMON = /home/james/code/course22/envs/include
QMAKE_INCDIR_XKBCOMMON_X11 = /home/james/code/course22/envs/include /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include
QMAKE_INCDIR_OPENGL = /home/james/code/course22/envs/include /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include/libdrm /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include
QMAKE_INCDIR_DRM = /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include/libdrm
QMAKE_INCDIR_EGL = /home/james/code/course22/envs/include /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include/libdrm /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include
QMAKE_DEPENDS_XCB_XLIB_CC = XCB XLIB
QMAKE_DEPENDS_XCB_XLIB_LD = XCB XLIB
QMAKE_DEPENDS_FREETYPE_CC = ZLIB
QMAKE_DEPENDS_FREETYPE_LD = ZLIB
QMAKE_INCDIR_FREETYPE = /home/james/code/course22/envs/include/freetype2
QMAKE_DEPENDS_FONTCONFIG_CC = FREETYPE
QMAKE_DEPENDS_FONTCONFIG_LD = FREETYPE
QMAKE_INCDIR_FONTCONFIG = /home/james/code/course22/envs/include /home/james/code/course22/envs/include/libxml2 /home/james/code/course22/envs/include
QMAKE_INCDIR_LIBJPEG = /home/james/code/course22/envs/include
QMAKE_DEPENDS_LIBPNG_CC = ZLIB
QMAKE_DEPENDS_LIBPNG_LD = ZLIB
QMAKE_INCDIR_LIBPNG = /home/james/code/course22/envs/include/libpng16 /home/james/code/course22/envs/include
QMAKE_DEPENDS_XCB_XINPUT_CC = XCB
QMAKE_DEPENDS_XCB_XINPUT_LD = XCB
QMAKE_DEPENDS_XCB_GLX_CC = XCB
QMAKE_DEPENDS_XCB_GLX_LD = XCB
QMAKE_INCDIR_X11SM = /croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/include
QMAKE_LIBS_XCB = -L/home/james/code/course22/envs/lib -lxcb -lxcb-shm
QMAKE_LIBS_XCB_ICCCM = -L/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64 -lxcb-icccm
QMAKE_LIBS_XCB_UTIL = -L/usr/lib64 -lxcb-atom -lxcb-aux -lxcb-event
QMAKE_LIBS_XCB_SHM = 
QMAKE_LIBS_XCB_IMAGE = -L/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64 -lxcb-image
QMAKE_LIBS_XCB_KEYSYMS = -L/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64 -lxcb-keysyms
QMAKE_LIBS_XCB_RANDR = -lxcb-randr
QMAKE_LIBS_XCB_RENDER = -lxcb-render
QMAKE_LIBS_XCB_RENDERUTIL = -L/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64 -lxcb-render-util
QMAKE_LIBS_XCB_SHAPE = -lxcb-shape
QMAKE_LIBS_XCB_SYNC = -lxcb-sync
QMAKE_LIBS_XCB_XFIXES = -lxcb-xfixes
QMAKE_LIBS_XCB_XINERAMA = -lxcb-xinerama
QMAKE_LIBS_XCB_XKB = -lxcb-xkb
QMAKE_LIBS_XKBCOMMON = -L/home/james/code/course22/envs/lib -lxkbcommon
QMAKE_LIBS_XKBCOMMON_X11 = -L/home/james/code/course22/envs/lib -lxkbcommon-x11 -lxkbcommon
QMAKE_LIBS_OPENGL = -L/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64 -lGL
QMAKE_LIBS_DRM = -L/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64 -ldrm
QMAKE_LIBS_EGL = -L/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64 -lEGL
QMAKE_LIBS_XLIB = -lXext -lX11 -lm
QMAKE_LIBS_XCB_XLIB = -L/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64 -lX11-xcb
QMAKE_LIBS_FREETYPE = -L/home/james/code/course22/envs/lib -lfreetype
QMAKE_LIBS_FONTCONFIG = -lfontconfig
QMAKE_LIBS_LIBJPEG = -L/home/james/code/course22/envs/lib -ljpeg
QMAKE_LIBS_LIBPNG = -L/home/james/code/course22/envs/lib -lpng16
QMAKE_LIBS_XCB_XINPUT = -lxcb-xinput
QMAKE_LIBS_XCB_GLX = -lxcb-glx
QMAKE_LIBS_X11SM = -L/croot/qt-main_1693210824277/_build_env/bin/../x86_64-conda-linux-gnu/sysroot/usr/lib64 -lSM -lICE
